[package]
name = "dailyfetcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
pretty_env_logger = "0.4"
roux = "2.2.2"
teloxide = { version = "0.11", features = ["macros", "auto-send"] }
tokio = { version = "1.21.2", features = ["full"] }