[package]
name = "reddit_fetcher"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
pretty_env_logger = "0.4"
roux = "2.2.2"
teloxide = { version = "0.11", features = ["macros", "auto-send"] }
tokio = { version = "1.21.2", features = ["full"] }
strum = "0.24.1"
strum_macros = "0.24"
serde = "1.0.147"
serde_json = "1.0.87"
sqlx = { version = "0.6", features = [ "runtime-tokio-rustls", "sqlite" ] }

[dependencies.uuid]
version = "1.2.1"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]